

services:

  php:
    build:
      context: .   
    depends_on:
       - mariadb 
    ports: 
      - "80:8181"  
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: forge
      DB_USERNAME: forge
      DB_PASSWORD: root
    

  mariadb:
    # container_name: maria_db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forge
      MYSQL_USER: forge
      MYSQL_PASSWORD: root
    volumes:
      - mariadb:/db
    ports:
      - '3306:3306'

volumes:
    mariadb: